### ISSUE TITLE
In server not support?

### ISSUE THREAD

**Issue by addpromax** [westernat/RevelationaryJS#1]
[18:39:46 ERROR]: Attempted to load class de/dafuqs/revelationary/ClientRevelationHolder for invalid dist DEDICATED_SERVER
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:112)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.5/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.NoClassDefFoundError: de/dafuqs/revelationary/ClientRevelationHolder
        at TRANSFORMER/eventhorizon@1.20.1-1.1.0/de.dafuqs.revelationary.api.revelations.RevealingCallback.register(RevealingCallback.java:36)
        at TRANSFORMER/revjs@2001forge-1.1.0/org.mesdag.revjs.revelation.RevelationEventJS.<init>(RevelationEventJS.java:22)
        at TRANSFORMER/revjs@2001forge-1.1.0/org.mesdag.revjs.revelation.RevelationEventJS.<clinit>(RevelationEventJS.java:18)
        at TRANSFORMER/revjs@2001forge-1.1.0/org.mesdag.revjs.RevJSPlugin.onServerReload(RevJSPlugin.java:22)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at TRANSFORMER/kubejs@2001.6.5-build.14/dev.latvian.mods.kubejs.util.KubeJSPlugins.forEachPlugin(KubeJSPlugins.java:116)
        at TRANSFORMER/kubejs@2001.6.5-build.14/dev.latvian.mods.kubejs.server.ServerScriptManager.wrapResourceManager(ServerScriptManager.java:99)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader$PackConfig.localvar$cmg000$injectKubeJSPacks(WorldLoader.java:515)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader$PackConfig.m_214399_(WorldLoader.java:80)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:28)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.lambda$main$2(Main.java:221)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:777)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:220)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: de.dafuqs.revelationary.ClientRevelationHolder
        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:157)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 28 more

**Comment by addpromax** [comment]
This issue is not resolved. The reason for closing is not completion.
